# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EVSnGEOzVOTZNe0wluJKK6LyQSzE-ljY
"""

fruits = ["Apple", "Pear", "Orange"]

try:
  user_index = int(input())
  the_pie = fruits[user_index]

except IndexError:
  print('Fruit Pie!')

else:
  print(f"{the_pie} pie")

facebook_posts = [
    {'Likes': 21, 'Comments': 2},
    {'Likes': 13, 'Comments': 2, 'Shares': 1},
    {'Likes': 33, 'Comments': 8, 'Shares': 3},
    {'Comments': 4, 'Shares': 2},
    {'Comments': 1, 'Shares': 1},
    {'Likes': 19, 'Comments': 3}
]

def count_likes(posts):

    total_likes = 0
    for post in posts:
      try:
        total_likes = total_likes + post['Likes']
      except KeyError:
        pass

    return total_likes


count_likes(facebook_posts)