# -*- coding: utf-8 -*-
"""day 026 of 100

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ApTduN4Y4RmbYgYrXFfG2vpGN3y7su3w
"""

numbers = [1,2,3]
new_numbers = [item + 1 for item in numbers]
print(new_numbers)

name = 'Aria'
new_list = [letter for letter in name]
print(new_list)

double_list = [n * 2 for n in range(1, 5)]
print(double_list)

numbers = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55]
squared_numbers = [num * num for num in numbers]
print(squared_numbers)

list_of_strings = ['9', '0', '32', '8', '2', '8', '64', '29', '42', '99']
numbers = [int(num) for num in list_of_strings]
result = [evens for evens in numbers if evens % 2 == 0]
print(result)

sentence = input()
result2 = {word:len(word) for word in sentence.split()}
print(result2)

weather_c = {"Monday": 12, "Tuesday": 14, "Wednesday": 15, "Thursday": 14, "Friday": 21, "Saturday": 22, "Sunday": 24}
weather_f = {day:temp * 9/5 + 32 for (day, temp) in weather_c.items()}
print(weather_f)

import pandas as pd
df = pd.read_csv('nato_phonetic_alphabet.csv')

#TODO 1. Create a dictionary in this format:

new_dict = {row.letter:row.code for (index, row) in df.iterrows()}

#TODO 2. Create a list of the phonetic code words from a word that the user inputs.
gone_through = False
while not gone_through:
  user_input = input("What's the word you want to turn into code? ").upper()

  try:
    code = [new_dict[letter] for letter in user_input]

  except KeyError:
    print('Sorry, only letters in alphabet please!!!')

  else:
    print(code)
    gone_through = True